version: '3.5'

services:
  frontend:
    container_name: full_frontend
    build: ./FRONT-END
    ports: 
      - 8100:8100 
    restart: on-failure
    volumes:
      - front_end:/usr/src/front_end/
    depends_on:
      - api
    networks:
      - fullstack

  api:
    container_name: full_api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/api/
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
    networks:
      - fullstack

  fullstack-postgres:
     image: postgres:latest
     container_name: full_db_postgres
     environment:
       - POSTGRES_USER=${DB_USER}  
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME}
       - DATABASE_HOST=${DB_HOST} 
     ports:
       - '5432:5432'
     volumes:
       - database_postgres:/var/lib/postgresql/data
     networks:
       - fullstack
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #      - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - fullstack
  #   restart: unless-stopped

  
  # fullstack-mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports: 
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_HOST=${DB_HOST} 
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - fullstack
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - fullstack-mysql
  #   environment:
  #     - PMA_HOST=fullstack-mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - fullstack


volumes:
  front_end:
  api:
  database_postgres:                  # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge

